### ISSUE TITLE
Support parsing of kubeconfig with extra fields

### ISSUE THREAD

**Issue by mgreyo** [sky-uk/osprey#68]
The way in which some tooling modifies your existing ~/.kube/config doesn't behave well with the unmarshal that happens inside osprey.

It gets confused trying to parse the `cluster.extensions` blocks and errors out.

e.g. minikube inserts this into ~/.kube/config:
```yaml
- cluster:
    certificate-authority: /Users/itme/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 03 Aug 2021 15:56:31 BST
        provider: minikube.sigs.k8s.io
        version: v1.21.0
      name: cluster_info
    server: https://127.0.0.1:49960
  name: minikube
```

Attempting to log into any group after this extra field is introduced causes all parsing to fail.

It can be replicated by adding in any field that osprey isn't aware of, e.g.

```
- context:
    break-me:
    cluster: cluster-url
    user: cluster-user
  name: cluster-name
```

Could be related to old versions of some packages used for generating the config being unfamiliar with the new fields, namely:
- k8s.io/client-go/tools/clientcmd
- k8s.io/client-go/tools/clientcmd/api
